let
    Source = Excel.Workbook(File.Contents("D:\LILLY\DA\cloudyML\PowerBI Case Studies\Cutomer_churn_analysis.xlsx"), null, true),
    Cutomer_churn_analysis_Sheet = Source{[Item="Cutomer_churn_analysis",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Cutomer_churn_analysis_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"gender", type text}, {"SeniorCitizen", Int64.Type}, {"Partner", type text}, {"Dependents", type text}, {"tenure", Int64.Type}, {"PhoneService", type text}, {"MultipleLines", type text}, {"InternetService", type text}, {"OnlineSecurity", type text}, {"OnlineBackup", type text}, {"DeviceProtection", type text}, {"TechSupport", type text}, {"StreamingTV", type text}, {"StreamingMovies", type text}, {"Contract", type text}, {"PaperlessBilling", type text}, {"PaymentMethod", type text}, {"MonthlyCharges", type number}, {"TotalCharges", type number}, {"Churn", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Yes","1",Replacer.ReplaceText,{"Partner"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","No","0",Replacer.ReplaceText,{"Partner"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"Partner", Int64.Type}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type1","Yes","1",Replacer.ReplaceText,{"Dependents"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","No","0",Replacer.ReplaceText,{"Dependents"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value3",{{"Dependents", Int64.Type}}),
    #"Replaced Value4" = Table.ReplaceValue(#"Changed Type2","Yes","1",Replacer.ReplaceText,{"PhoneService"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","No","0",Replacer.ReplaceText,{"PhoneService"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value5",{{"PhoneService", Int64.Type}}),
    #"Replaced Value6" = Table.ReplaceValue(#"Changed Type3","No phone service","0",Replacer.ReplaceText,{"MultipleLines"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","No","0",Replacer.ReplaceText,{"MultipleLines"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Yes","1",Replacer.ReplaceText,{"MultipleLines"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","No internet service","0",Replacer.ReplaceText,{"OnlineSecurity"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Yes","1",Replacer.ReplaceText,{"OnlineSecurity"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","No","0",Replacer.ReplaceText,{"OnlineSecurity"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value11",{{"OnlineSecurity", Int64.Type}}),
    #"Replaced Value12" = Table.ReplaceValue(#"Changed Type4","No internet service","0",Replacer.ReplaceText,{"OnlineBackup"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","No internet service","0",Replacer.ReplaceText,{"DeviceProtection"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","No internet service","0",Replacer.ReplaceText,{"TechSupport"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","No internet service","0",Replacer.ReplaceText,{"StreamingTV", "StreamingMovies"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","Yes","1",Replacer.ReplaceText,{"OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","No","0",Replacer.ReplaceText,{"OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Replaced Value17",{{"OnlineBackup", Int64.Type}, {"DeviceProtection", Int64.Type}, {"TechSupport", Int64.Type}, {"StreamingTV", Int64.Type}, {"StreamingMovies", Int64.Type}}),
    #"Replaced Value18" = Table.ReplaceValue(#"Changed Type5","Yes","1",Replacer.ReplaceText,{"PaperlessBilling"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","No","0",Replacer.ReplaceText,{"PaperlessBilling"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value19",{{"PaperlessBilling", Int64.Type}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type6", "Churn", "Churn - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Churn - Copy", "Churn Flag"}}),
    #"Replaced Value20" = Table.ReplaceValue(#"Renamed Columns","Yes","1",Replacer.ReplaceText,{"Churn Flag"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","No","0",Replacer.ReplaceText,{"Churn Flag"}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Replaced Value21",{{"Churn Flag", Int64.Type}, {"MultipleLines", Int64.Type}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Changed Type7", "InternetService", "InternetService - Copy"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column1",{"Customer ID", "gender", "SeniorCitizen", "Partner", "Dependents", "tenure", "PhoneService", "MultipleLines", "InternetService - Copy", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn", "Churn Flag"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"InternetService - Copy", "InternetFlag"}}),
    #"Replaced Value22" = Table.ReplaceValue(#"Renamed Columns1","No","0",Replacer.ReplaceText,{"InternetFlag"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","DSL","1",Replacer.ReplaceText,{"InternetFlag"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","Fiber optic","1",Replacer.ReplaceText,{"InternetFlag"}),
    #"Changed Type8" = Table.TransformColumnTypes(#"Replaced Value24",{{"InternetFlag", Int64.Type}}),
    #"Inserted Sum" = Table.AddColumn(#"Changed Type8", "Addition", each List.Sum({[PhoneService], [MultipleLines], [InternetFlag], [OnlineSecurity], [OnlineBackup], [DeviceProtection], [TechSupport], [StreamingTV], [StreamingMovies]}), Int64.Type),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Sum",{{"Addition", "Total Services"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns2", each true),
    #"Changed Type9" = Table.TransformColumnTypes(#"Filtered Rows",{{"tenure", type text}})
in
    #"Changed Type9"